### ISSUE TITLE
Licensing & usage questions

### ISSUE THREAD

**Issue by shakeelmohamed** [MrAnyone/YouTube-Audio-Visualizer#1]
Hey Mateus,

I've been playing around with the YouTube API over the past year and I've created a few interesting projects, mainly [Zen Audio Player](https://github.com/zen-audio-player/zen-audio-player.github.io) for listening to YouTube videos without the visuals. I have an open issue for adding an audio visualizer (see https://github.com/zen-audio-player/zen-audio-player.github.io/issues/204) - and yours works brilliantly! 🎉 

I didn't find any licensing information in your repo, and I'm wondering if you'd like to make a decision about usage rights (GitHub has a nice guide at http://choosealicense.com/). I would love to use some of your code to bring an audio visualizer to the [Zen Audio Player website](https://zenplayer.audio/).
Do we have your permission to do so? More importantly, are you interested in helping us add this feature?

I definitely appreciate the work you've done on this extension, hope to hear from you soon!
-Shakeel

PS: Feel free to shoot me an email (on my profile page) if you want to discuss this privately 😄

**Comment by MatMercer** [comment]
Yes! Sure! I'm glad to see that someone is interested in it!

While my repository was growing, I noticed that make a extension _exactly for that_ isn't the best way to make a audio visualizer. It is better to make a visualizer that is a module, to make it usable everywhere. Some code of it is made this way, for example, it creates an object called 'vis' and it have all the settings in it.

Another important thing is that you _must_ try to use webgl, because it is _super fast_. Using another type of render may cause bad behavior. As you can see here:
https://www.youtube.com/watch?v=a_5jgNN1p7w
The first version of it was made with div's and css xD make it veeery 'laggy'.
The second version was made with canvas, again, causing lag.
WebGL rules! Hah.

Well I would like to see my repository grow, and I'll be glad to help with anything; I have some plans about making any sort of scenes.
. Oh, currently the branch 'settings' have localstorage settings implementation, so it is more flexible.
My coding style isn't so good, I need to add a design pattern to it because it is quite messy.
I'll add a license to my repository and you can start working on it anytime hah.

Thanks, ~MrAnyone.

**Comment by MatMercer** [comment]
Done, I added the MIT license.

**Comment by shakeelmohamed** [comment]
Perfect, thanks for the speedy reply! I'll let you know if I run into any issues along the way 👍
